# -*- coding: utf-8 -*-
"""WinePricePredictionProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZwHoDX1emgPRz64oIq2w703ZXQNhUPF

**REMEMBER WE ONLY HAVE 100 ROWS OF DATA 80 ARE FOR TRAINING AND 20 FOR TESTING SO DO NOT EXPECT TO HAVE VERY HIGH ACCURACY RESULTS UNLESS YOU GENERATED ADDITIONAL RANDOM DATASETS BASED ON MEAN AND MEDIANS TO EXTEND THE DATA SET SIZE **
"""

#import pandas as pd
#import numpy as np
#import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats # imported library to use boxcox because logX alone wasnt that good
import pickle
#from sklearn.model_selection import train_test_split
#from sklearn.ensemble import RandomForestRegressor
#from sklearn.metrics import mean_squared_error, r2_score

# ------------------------------
# 1️⃣ Core libraries
# ------------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------
# 2️⃣ Preprocessing
# ------------------------------
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler

# ------------------------------
# 3️⃣ Regression models
# ------------------------------
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

# ------------------------------
# 4️⃣ Metrics
# ------------------------------
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("WINE_PRICE.csv")

df

df.shape #ti know rows and columns

df.columns#to see column names

df.info()

df.isnull().sum()



df.describe()

import matplotlib.pyplot as plt

col = 'Price'  # example column

plt.hist(df[col], bins=20, alpha=0.5, color='skyblue', edgecolor='black')
plt.axvline(df[col].mean(), color='red', linestyle='dashed', linewidth=2, label=f"Mean = {df[col].mean():.2f}")
plt.axvline(df[col].median(), color='green', linestyle='dashed', linewidth=2, label=f"Median = {df[col].median():.2f}")
plt.legend()
plt.title(f"{col} Distribution: Mean vs Median")
plt.show()

#What you see
#Red dashed line = mean
#Green dashed line = median
#If lines overlap → symmetric
#If lines separated → skewed

#how can I know which column is the cause of all these Skews ??

# Calculate mean, median, skew for all columns
summary = pd.DataFrame({
    'Mean': df.mean(),
    'Median': df.median(),
    'Skew': df.skew()
})
print(summary)

#we are checking whether outliers are rare values or real outliers
# List of columns to check
columns = ['Volatile_Acidity', 'Alcohol']

for col in columns:
    print(f"--- Outlier Analysis for {col} ---")

    # Calculate Q1, Q3, and IQR
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    # Define lower and upper bounds
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Identify outliers
    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print("Number of outliers:", len(outliers))
    print(outliers[[col, 'Price']].sort_values(col, ascending=False))

    # Plot boxplot
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()  # Ensures each plot shows in Colab

#we are checking whether outliers are rare values or real outliers
# List of columns to check
columns = ['Volatile_Acidity', 'Alcohol']

for col in columns:
    plt.figure(figsize=(8,5))
    plt.scatter(df[col], df['Price'], alpha=0.6)
    plt.xlabel(col)
    plt.ylabel('Price')
    plt.title(f"{col} vs Price")
    plt.show()  # Makes sure each scatter plot shows in Colab

#managing skewed data
df['Volatile_Acidity_log'] = np.log1p(df['Volatile_Acidity']) #log since its a right skew also for left skew we can use log
df['Alcohol_log'] = np.log1p(df['Alcohol'])

#checking skews after fixing
df[['Volatile_Acidity_log','Alcohol_log']].skew()

#checking skews after fixing
import seaborn as sns
sns.histplot(df['Volatile_Acidity_log'], kde=True)
sns.histplot(df['Alcohol_log'], kde=True)

# Volatile_Acidity must be strictly positive
df['Volatile_Acidity_log_boxcox'], _ = stats.boxcox(df['Volatile_Acidity_log'] + 1e-6)  # add tiny value if zeros exist

print(df[['Volatile_Acidity_log_boxcox','Alcohol_log']].skew())

import matplotlib.pyplot as plt
import seaborn as sns

for col in ['Volatile_Acidity']:
    plt.figure(figsize=(6,3))
    sns.histplot(df[col], kde=True, color='skyblue')
    plt.axvline(df[col].mean(), color='red', linestyle='dashed', label='Mean')
    plt.axvline(df[col].median(), color='green', linestyle='dashed', label='Median')
    plt.legend()
    plt.title(f'{col} Distribution After Final Transformation')
    plt.show()

"""REMARK !!!!
I COULD HAVE REMOVED LOGX ON VOLATILE ACIDITY AND SIMPLY USE COXBOX IT WILL DIRECTLY GIVE GOOD RESULTS
"""

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.histplot(df['Volatile_Acidity'], kde=True, color='skyblue')
plt.title('Original Volatile_Acidity')

plt.subplot(1,2,2)
sns.histplot(df['Volatile_Acidity_log_boxcox'], kde=True, color='lightgreen')
plt.title('Box-Cox Transformed Volatile_Acidity')

plt.show()

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.histplot(df['Alcohol'], kde=True, color='skyblue')
plt.title('Original Alcohol')

plt.subplot(1,2,2)
sns.histplot(df['Alcohol_log'], kde=True, color='lightgreen')
plt.title('Log Transformed Alcohol')

plt.show()

# Compute correlations with target
corr_target = df.corr()['Price'].sort_values(ascending=False)
print(corr_target)

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

"""| Feature                                 | Correlation           | Interpretation                                      |
| --------------------------------------- | --------------------- | --------------------------------------------------- |
| **Alcohol / Alcohol_log**               | 0.8017 / 0.7597       | Strong positive → keep                              |
| **Volatile_Acidity / log / log_boxcox** | -0.36 / -0.32 / -0.22 | Strong negative → keep                              |
| Citric_Acid                             | 0.1256                | Very weak → minor effect                            |
| Fixed_Acidity                           | 0.0811                | Almost zero → negligible                            |
| Density                                 | 0.0410                | Almost zero → negligible                            |
| Free_Sulfur_Dioxide                     | 0.0325                | Almost zero → negligible                            |
| Residual_Sugar                          | -0.0015               | Zero correlation → useless for linear relationships |
| Total_Sulfur_Dioxide                    | -0.0157               | Almost zero → negligible                            |
| pH                                      | -0.1294               | Weak → minor effect                                 |
| Chlorides                               | -0.1832               | Weak negative → minor effect                        |

"""

print(df)

# Remove leading/trailing spaces from all column names
df.columns = df.columns.str.strip()

print(df.columns)

# Drop raw Alcohol and Volatile_Acidity
df = df.drop(columns=['Alcohol', 'Volatile_Acidity','Volatile_Acidity_log'])
# Keep: Alcohol_log and Volatile_Acidity_log_boxcox

print(df.columns)

# Ratios
df['Sulfur_Ratio'] = df['Free_Sulfur_Dioxide'] / (df['Total_Sulfur_Dioxide'] + 1e-6)
df['Sugar_Acidity_Ratio'] = df['Residual_Sugar'] / (df['Fixed_Acidity'] + 1e-6)
df['Alcohol_to_Acidity'] = df['Alcohol_log'] / (df['Fixed_Acidity'] + 1e-6)
df['Volatile_to_Fixed_Acidity'] = df['Volatile_Acidity_log_boxcox'] / (df['Fixed_Acidity'] + 1e-6)

# Interactions
df['Alcohol_x_CitricAcid'] = df['Alcohol_log'] * df['Citric_Acid']
df['ResidualSugar_x_Alcohol'] = df['Residual_Sugar'] * df['Alcohol_log']

# Transformations
df['Residual_Sugar_log'] = np.log1p(df['Residual_Sugar'])
df['pH_squared'] = df['pH']**2

# Compute correlation matrix
corr_matrix = df.corr()

# Correlation of all features with Price
corr_with_price = corr_matrix['Price'].sort_values(ascending=False)
print(corr_with_price)

#Random Forest will automatically assign near-zero importance
#to useless features, so dropping them is optional.
df = df.drop(columns=[
    'Residual_Sugar',
    'Sugar_Acidity_Ratio',
    'Fixed_Acidity',
    'Sulfur_Ratio',
    'Residual_Sugar_log',
    'Total_Sulfur_Dioxide',
    'Density',
    'Free_Sulfur_Dioxide'
])

print(df.columns)

# Check min, max, mean, std for all features to see if scaling is needed
#BUT RANDOM FOREST DOESNT REQUIRE SCALING!!!!
#df.describe()

#BUT IF I WANT TO SCALE THEN
#from sklearn.preprocessing import StandardScaler

#scaler = StandardScaler()
#X_scaled = scaler.fit_transform(df.drop(columns='Price'))

#If you set random_state to a fixed number (like 42),
#every time you run this code, you will get exactly the same split of data into training
#and testing sets.
#If you don’t set it or set it to None,
#the split will be random each time you run the code,
#so your train/test sets will be different each time.

# Features (drop target)
#X = df.drop(columns='Price')

# Target
#y = df['Price']

# Train-test split (e.g., 80% train, 20% test)
#X_train, X_test, y_train, y_test = train_test_split(
#    X, y, test_size=0.2, random_state=42
#)

#print("Train shape:", X_train.shape)
#print("Test shape:", X_test.shape)

# =========================================
# 4️⃣ Initialize and train Random Forest
# =========================================
#rf = RandomForestRegressor(
#    n_estimators=100,   # number of trees
#    max_depth=None,     # allow full growth
#    random_state=42
#)

#rf.fit(X_train, y_train)

# =========================================
# 5️⃣ Make predictions
# =========================================
#y_pred = rf.predict(X_test)

# =========================================
# 6️⃣ Evaluate model
# =========================================
#mse = mean_squared_error(y_test, y_pred)
#rmse = mse**0.5
#r2 = r2_score(y_test, y_pred)

#print(f"RMSE: {rmse:.2f}")
#print(f"R^2: {r2:.2f}")

# =========================================
# 7️⃣ Feature importance
# =========================================
#importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)

# Plot feature importance
#plt.figure(figsize=(12,6))
#importances.plot(kind='bar')
#plt.title("Random Forest Feature Importance")
#plt.ylabel("Importance")
#plt.show()

# Optional: see top 10 features
#print("Top 10 features by importance:")
#print(importances.head(10))



# Original features
X = df.drop(columns=['Price'])
y = df['Price']

# 1️⃣ Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 2️⃣ Convert scaled array back to DataFrame to keep column names
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

# 3️⃣ Check the first few rows to see scaled values
print(X_scaled_df.head())

# 4️⃣ Train-test split for scaled models
X_train_scaled, X_test_scaled, y_train_scaled, y_test_scaled = train_test_split(
    X_scaled_df, y, test_size=0.2, random_state=42
)

# =============================
# 1️⃣ Prepare Data
# =============================

# X = all features except the target 'Price'
# df.drop(columns=['Price']) removes the 'Price' column from the DataFrame
# This is our feature matrix for training the models
X = df.drop(columns=['Price'])

# y = target variable, the column we want to predict
# Here it's the Price of wine
# Optional: if Price is highly skewed, you could use log-transform:
# y = np.log1p(df['Price']) to stabilize variance
y = df['Price']

# =============================
# 2️⃣ Scale features for certain models
# =============================

# Initialize a StandardScaler object
# StandardScaler removes the mean and scales each feature to unit variance
# (mean=0, std=1)
scaler = StandardScaler()

# Fit the scaler to X and transform it
# fit_transform learns the mean & std from X and applies scaling
# Returns a NumPy array (column names lost here)
X_scaled = scaler.fit_transform(X)

# Convert the scaled NumPy array back to a DataFrame
# Keep the original column names using columns=X.columns
# Now X_scaled_df has the same feature names but scaled values
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

# -----------------------------
# Train-test split
# -----------------------------

# Split unscaled features for tree-based models
# Random state 42 ensures reproducibility (same split every run)
# test_size=0.2 → 20% of data goes to testing (here 20 rows out of 100)
X_train_tree, X_test_tree, y_train_tree, y_test_tree = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Split scaled features for models that need scaling (Linear, Ridge, Lasso, KNN, SVR)
X_train_scaled, X_test_scaled, y_train_scaled, y_test_scaled = train_test_split(
    X_scaled_df, y, test_size=0.2, random_state=42
)

# =============================
# 3️⃣ Define models and scaling requirement
# =============================

# Dictionary of models and whether they need scaled features or not
# Key = model name (string)
# Value = tuple of (model instance, 'scaled' or 'tree')
models = {
    # RandomForestRegressor → tree-based, does not require scaling
    # n_estimators=500 → number of trees, more trees → more stable predictions
    "RandomForest": (RandomForestRegressor(random_state=42, n_estimators=500), "tree"),

    # GradientBoostingRegressor → tree-based, boosting ensemble, also doesn't require scaling
    "GradientBoosting": (GradientBoostingRegressor(random_state=42, n_estimators=500), "tree"),

    # DecisionTreeRegressor → single tree, tree-based
    "DecisionTree": (DecisionTreeRegressor(random_state=42), "tree"),

    # LinearRegression → needs scaled features for best performance
    "LinearRegression": (LinearRegression(), "scaled"),

    # Ridge → linear regression with L2 regularization, scaled features
    "Ridge": (Ridge(), "scaled"),

    # Lasso → linear regression with L1 regularization, scaled features
    "Lasso": (Lasso(), "scaled"),

    # SVR → Support Vector Regressor, highly sensitive to feature scale
    "SVR": (SVR(), "scaled"),

    # KNN → distance-based, sensitive to scale, needs scaling
    "KNN": (KNeighborsRegressor(), "scaled")
}

# =============================
# 4️⃣ Train, predict, evaluate
# =============================

# Initialize empty list to store results for each model
results = []

# Loop through all models
for name, (model, scale_type) in models.items():

    # Select proper X depending on whether the model needs scaled data
    if scale_type == 'scaled':
        # Use the scaled features
        X_tr, X_te, y_tr, y_te = X_train_scaled, X_test_scaled, y_train_scaled, y_test_scaled
    else:
        # Use unscaled features for tree-based models
        X_tr, X_te, y_tr, y_te = X_train_tree, X_test_tree, y_train_tree, y_test_tree

    # -----------------------------
    # Train the model
    # -----------------------------
    # Fit the model on training data
    # model learns patterns from X_tr to predict y_tr
    model.fit(X_tr, y_tr)

    # -----------------------------
    # Predict on test set
    # -----------------------------
    # model predicts Price (or y) for unseen test data X_te
    y_pred = model.predict(X_te)

    # -----------------------------
    # Compute metrics
    # -----------------------------
    # Mean Squared Error → average squared difference between predicted and actual
    mse = mean_squared_error(y_te, y_pred)

    # RMSE → square root of MSE, same units as target (Price)
    rmse = np.sqrt(mse)

    # R² score → proportion of variance explained by the model
    # 1 = perfect, 0 = predicts mean, negative = worse than mean
    r2 = r2_score(y_te, y_pred)

    # Cross-validated R² → average R² on 5 folds of training data
    # Ensures the model generalizes well and is not overfitting
    cv_scores = cross_val_score(model, X_tr, y_tr, cv=5, scoring='r2')

    # Append metrics for this model to results list
    results.append({
        "Model": name,
        "RMSE": rmse,                     # Test RMSE
        "R2": r2,                         # Test R²
        "CV_R2_mean": cv_scores.mean()    # Average CV R²
    })

# =============================
# 5️⃣ Results DataFrame & Plot
# =============================

# Convert results list to DataFrame
# Sort by CV_R2_mean descending → best performing model first
results_df = pd.DataFrame(results).sort_values(by="CV_R2_mean", ascending=False)

# Print the results table
print(results_df)

# Plot bar chart of mean CV R² for all models
plt.figure(figsize=(12,6))                      # Figure size
plt.bar(results_df['Model'], results_df['CV_R2_mean'], color='skyblue')  # Bar chart
plt.ylabel("Mean CV R²")                        # Y-axis label
plt.title("Regression Model Comparison (5-Fold CV)")  # Chart title
plt.xticks(rotation=45)                          # Rotate X labels for readability
plt.show()

# =============================
# 6️⃣ Optional: Feature importance for tree-based models
# =============================

# Loop through models to show feature importance only for tree-based models
for name, (model, scale_type) in models.items():
    if scale_type == 'tree':  # Only for RandomForest, GradientBoosting, DecisionTree
        # Get feature importance as a Series, indexed by column names
        feat_imp = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)

        # Print feature importance for this model
        print(f"\n{name} Feature Importance:\n", feat_imp)

"""The below ensures:

Correct column order
No missing columns
No extra columns
"""

with open('rf_features.pkl', 'wb') as f:
    pickle.dump(X.columns.tolist(), f)

with open('rf_features.pkl', 'rb') as f:
    feature_names = pickle.load(f)

print(feature_names)

# Pick the RandomForest model from your dictionary
rf_model = models['RandomForest'][0]  # models['RandomForest'] = (model_instance, "tree")

# Train it on the tree-based training data
rf_model.fit(X_train_tree, y_train_tree)


# Save the trained model
with open('randomforest_model.pkl', 'wb') as f:  # wb = write binary
    pickle.dump(rf_model, f)